import { makeStyles } from "@material-ui/core";
import { customScrollbar } from "../../../styles/materialUi";

const useStyles = makeStyles((theme) => ({
  root: {
    width: "100%",
    margin: "auto",
    background: "#fff",
    borderRadius: 24,
    boxShadow: "0 4px 24px rgba(45, 108, 223, 0.08)",
    padding: "32px 24px",
    marginTop: 40,
    marginBottom: 40,
    [theme.breakpoints.down("sm")]: {
      padding: "20px 16px",
      marginTop: 24,
      marginBottom: 24,
      borderRadius: 16,
    },
  },
  appBarRoot: {
    backgroundColor: "transparent",
    boxShadow: "none",
  },
  indicator: {
    backgroundColor: "transparent",
  },
  tapRoot: {
    color: "#333",
    opacity: 1,
    fontSize: 16,
    fontWeight: 600,
    transition: "all 0.3s ease",
    "&:hover": {
      color: "#2d6cdf",
      transform: "translateY(-2px)",
    },
  },
  selectedTap: {
    color: "#2d6cdf",
    fontSize: 18,
    fontWeight: 700,
  },
  noname: {
    "& .MuiBox-root": {
      paddingTop: (props) => (props.isMobile ? 0 : 32),
    },
  },
  tabList: {
    display: "flex",
    gap: 12,
    marginBottom: 24,
    overflowX: "auto",
    paddingBottom: 12,
    ...customScrollbar,
  },
  tabItem: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    background: "#fff",
    color: "#333",
    borderRadius: 16,
    border: "2px solid #e0e0e0",
    padding: "12px",
    fontWeight: 600,
    fontSize: 14,
    cursor: "pointer",
    transition: "all 0.3s ease",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    maxWidth: 90,
    minWidth: 90,
    minHeight: 90,
    height: 90,
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.04)",
    textAlign: "center",
    "&:hover": {
      background: "#e6eaf3",
      color: "#2d6cdf",
      borderColor: "#2d6cdf",
      transform: "translateY(-2px)",
      boxShadow: "0 4px 12px rgba(45, 108, 223, 0.1)",
    },
    [theme.breakpoints.down("sm")]: {
      padding: "8px",
      fontSize: 12,
      maxWidth: 70,
      minWidth: 70,
      minHeight: 70,
      height: 70,
    },
  },
  tabItemActive: {
    background: "#e6eaf3",
    color: "#2d6cdf",
    borderColor: "#2d6cdf",
    boxShadow: "0 4px 12px rgba(45, 108, 223, 0.15)",
  },
  listDay: {
    display: "flex",
    gap: 16,
    overflowX: "auto",
    padding: "16px 24px",
    background: "#f8f9fa",
    borderRadius: 16,
    boxShadow: "0 2px 12px rgba(0, 0, 0, 0.04)",
    ...customScrollbar,
  },
  dayItem: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    minWidth: 80,
    padding: "12px 16px",
    fontWeight: 600,
    color: "#333",
    background: "#fff",
    borderRadius: 12,
    border: "2px solid #e0e0e0",
    cursor: "pointer",
    transition: "all 0.3s ease",
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.04)",
    "&:hover": {
      background: "#e6eaf3",
      borderColor: "#2d6cdf",
      transform: "translateY(-2px)",
      boxShadow: "0 4px 12px rgba(45, 108, 223, 0.1)",
    },
    "& p": {
      margin: 0,
      lineHeight: 1.4,
    },
    "& p:first-child": {
      fontSize: 20,
      fontWeight: 700,
      color: "#333",
    },
    "& p:last-child": {
      fontSize: 14,
      fontWeight: 500,
      color: "#666",
    },
    [theme.breakpoints.down("sm")]: {
      minWidth: 70,
      padding: "8px 12px",
      "& p:first-child": {
        fontSize: 18,
      },
      "& p:last-child": {
        fontSize: 12,
      },
    },
  },
  dayItemActive: {
    background: "#e6eaf3",
    borderColor: "#2d6cdf",
    boxShadow: "0 4px 12px rgba(45, 108, 223, 0.15)",
    "& p:first-child": {
      color: "#2d6cdf",
    },
    "& p:last-child": {
      color: "#2d6cdf",
    },
  },
  rapItem: {
    marginBottom: 16,
    padding: "16px",
    background: "#fff",
    borderRadius: 16,
    border: "2px solid #e0e0e0",
    cursor: "pointer",
    transition: "all 0.3s ease",
    "&:hover": {
      background: "#f8f9fa",
      borderColor: "#2d6cdf",
      transform: "translateY(-2px)",
      boxShadow: "0 4px 12px rgba(45, 108, 223, 0.1)",
    },
  },
  rapItemActive: {
    background: "#e6eaf3",
    borderColor: "#2d6cdf",
    boxShadow: "0 4px 12px rgba(45, 108, 223, 0.15)",
    "& h3": {
      color: "#2d6cdf",
    },
  },
  cumRapItem: {
    padding: 0,
    margin: 0,
    "& .MuiAccordion-root": {
      minHeight: "70px",
      "& .MuiAccordionSummary-root": {
        minHeight: "70px",
        padding: "0 16px",
        display: "flex",
        alignItems: "center",
      },
      "& .MuiAccordionDetails-root": {
        padding: "16px",
        overflow: "auto",
        maxHeight: "300px",
        ...customScrollbar,
      },
    },
  },
  wrapInfo: {
    flex: 1,
    marginLeft: "16px",
    "& h3": {
      color: "#2d6cdf",
      fontSize: "18px",
      fontWeight: 700,
      margin: 0,
      marginBottom: 4,
    },
    "& p": {
      color: "#666",
      fontSize: "14px",
      margin: 0,
    },
  },
  imgTheater: {
    width: "40px",
    height: "40px",
    objectFit: "contain",
    margin: 0,
    padding: 4,
    background: "#f8f9fa",
    borderRadius: 8,
    border: "2px solid #e0e0e0",
  },
  showtimeList: {
    display: "flex",
    flexWrap: "wrap",
    gap: 12,
    marginTop: 8,
  },
  showtimeItem: {
    background: "#fff",
    color: "#2d6cdf",
    borderRadius: 12,
    border: "2px solid #2d6cdf",
    padding: "10px 20px",
    fontWeight: 600,
    fontSize: "14px",
    cursor: "pointer",
    transition: "all 0.3s ease",
    boxShadow: "0 2px 8px rgba(45, 108, 223, 0.1)",
    "&:hover": {
      background: "#e6eaf3",
      color: "#2d6cdf",
      transform: "translateY(-2px)",
      boxShadow: "0 4px 12px rgba(45, 108, 223, 0.15)",
    },
  },
}));

export default useStyles;