import { makeStyles } from "@material-ui/core";
import { customScrollbar } from "../../../../styles/materialUi";

const useStyles = makeStyles((theme) => ({
  root: {
    width: "100%",
    margin: "auto",
    background: "#fff",
    borderRadius: 16,
    boxShadow: "0 2px 16px 0 rgba(250, 82, 56, 0.08)",
    padding: "24px 0 24px 0",
    marginTop: 32,
    marginBottom: 32,
    display: "flex",
    flexDirection: "column",
    [theme.breakpoints.down("sm")]: {
      padding: "12px 0 12px 0",
      marginTop: 16,
      marginBottom: 16,
      borderRadius: 10,
    },
  },
  tabList: {
    display: "flex",
    gap: 8,
    marginBottom: 18,
    overflowX: "auto",
    paddingBottom: 8,
    ...customScrollbar,
    flexWrap: "nowrap",
    minHeight: 60,
  },
  tabItem: {
    display: "flex",
    alignItems: "center",
    background: "#fff",
    color: "#222",
    borderRadius: 12,
    border: "1px solid #e0e0e0",
    padding: "8px 12px",
    fontWeight: 600,
    fontSize: 10,
    cursor: "pointer",
    transition: "all 0.2s",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    maxWidth: 120,
    boxShadow: "0 2px 4px rgba(0, 0, 0, 0.05)",
    [theme.breakpoints.down("sm")]: {
      padding: "6px 10px",
      fontSize: 12,
      maxWidth: 100,
    },
  },
  tabItemActive: {
    background: "#fff0f3",
    color: "#ff1744",
    borderColor: "#ff1744",
    boxShadow: "0 4px 8px rgba(255, 23, 68, 0.1)",
  },
  indicator: {
    backgroundColor: "transparent",
    width: 4,
    borderRadius: 2,
  },
  wrapper: {
    display: "flex",
    alignItems: "center",
    gap: 6,
  },
  logo: {
    width: 70,
    height: 70,
    objectFit: "contain",
    borderRadius: 6,
    background: "#f7f7fa",
    boxShadow: "0 1px 4px rgba(60,60,60,0.04)",
  },
  rightSection: {
    flex: 1,
    padding: "24px 32px",
    background: "transparent",
    [theme.breakpoints.down("sm")]: {
      padding: "12px 8px",
    },
  },
  cumRapList: {
    display: "flex",
    gap: 12,
    overflowX: "auto",
    background: "#fff0f3",
    borderRadius: 8,
    ...customScrollbar,
  },
  cumRapItem: {
    display: "flex",
    alignItems: "flex-start",
    padding: "0 0 0 0",
    gap: "12px",
    background: "#fff",
    borderRadius: 8,
    border: "1.5px solid #ececec",
    boxShadow: "0 1px 4px rgba(60,60,60,0.04)",
    marginBottom: 0,
    transition: "all 0.2s",
    cursor: "pointer",
    "&:hover": {
      background: "#f5f5f5",
      borderColor: "#ececec",
    },
    [theme.breakpoints.down("sm")]: {
      flexDirection: "column",
      gap: 8,
      padding: "8px 0 8px 0",
    },
  },
  cumRapItemActive: {
    background: "#e6eaf3",
    borderColor: "#2d6cdf",
    boxShadow: "0 2px 8px rgba(45,108,223,0.08)",
  },
  showtimeSection: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
    marginTop: 10,
  },
  showtimeItem: {
    background: "#fff",
    color: "#2d6cdf",
    borderRadius: 6,
    border: "1.5px solid #ececec",
    padding: "7px 16px",
    fontWeight: 600,
    fontSize: 11,
    cursor: "pointer",
    transition: "all 0.2s",
    boxShadow: "0 1px 4px rgba(60,60,60,0.04)",
    margin: "4px 6px 4px 0",
    "&:hover": {
      background: "#e6eaf3",
      color: "#2d6cdf",
      borderColor: "#2d6cdf",
    },
    "&.Mui-selected": {
      background: "#e6eaf3",
      color: "#2d6cdf",
      borderColor: "#2d6cdf",
      boxShadow: "0 2px 8px rgba(45,108,223,0.08)",
    },
  },
  noname: {
    "& .MuiBox-root": {
      paddingTop: (props) => (props.isMobile ? 0 : 24),
    },
  },
  listDay: {
    display: "flex",
    gap: 14,
    overflowX: "auto",
    padding: "0px 0 10px 0",
    background: "#fff",
    borderRadius: 10,
    boxShadow: "0 1px 4px rgba(60,60,60,0.04)",
    ...customScrollbar,
  },
  dayItem: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    minWidth: 28,
    padding: "6px 6px",
    fontWeight: 600,
    color: "#000",
    background: "#f5f5f5",
    borderRadius: 8,
    border: "1px solid #e0e0e0",
    cursor: "pointer",
    boxShadow: "0 2px 4px rgba(0, 0, 0, 0.1)",
    marginBottom: 0,
    transition: "all 0.2s",
    "&:hover": {
      background: "#e3f2fd",
    },
    "& p": {
      margin: 0,
      lineHeight: 1.2,
    },
    "& p:first-child": {
      fontSize: 14,
      fontWeight: 700,
      color: "#000",
    },
    "& p:last-child": {
      fontSize: 10,
      fontWeight: 400,
      color: "#000",
    },
    [theme.breakpoints.down("sm")]: {
      minWidth: 36,
      padding: "4px 4px",
      fontSize: 10,
      "& p:first-child": {
        fontSize: 11,
      },
      "& p:last-child": {
        fontSize: 8,
      },
    },
  },
  dayItemActive: {
    background: "#1976d2",
    color: "#fff",
    borderColor: "#1976d2",
    boxShadow: "0 2px 4px rgba(25, 118, 210, 0.2)",
    "& p:first-child": {
      color: "#fff",
    },
    "& p:last-child": {
      color: "#fff",
    },
  },
  rapItem: {
    marginBottom: 6,
    padding: "0px 0 0px 0",
    background: "#fff",
    borderRadius: 12,
    transition: "all 0.2s",
    cursor: "pointer",
    fontSize: 13,
    "&:hover": {
      background: "#f5f5f5",
    },
  },
  rapItemActive: {
    background: "#e3f2fd",
  },
  imgTheater: {
    width: 56,
    height: 56,
    objectFit: "cover",
    borderRadius: 8,
    border: "1px solid #eee",
    background: "#fafafa",
  },
  wrapInfo: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    marginLeft: 12,
    [theme.breakpoints.down("sm")]: {
      marginLeft: 0,
    },
    "& h3": {
      color: "#fa5238",
      fontSize: 18,
      fontWeight: 700,
      margin: 0,
    },
    "& p": {
      color: "#757575",
      fontSize: 14,
      margin: 0,
    },
  },
  showtimeList: {
    display: "flex",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 3,
    [theme.breakpoints.down("sm")]: {
      gap: 6,
    },
  },
  AccordionDetails: {
    padding: 0,
    margin: 0,
  },
  leftSection: {

    background: "#fff",

    padding: "0px 0",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    [theme.breakpoints.down("sm")]: {
      minWidth: 120,
      padding: "4px 0",
    },
  },
  tabRoot: {
    minWidth: "unset !important",
    minHeight: "unset !important",
    alignItems: "center",
    justifyContent: "center",
    minHeight: 70,
    width: 70,
    height: 70,
    padding: "0px 0px",
    borderRadius: 8,
    margin: "20px 20px 10px 10px",
    background: "#fff",
    transition: "all 0.2s",
    textTransform: "none",
    fontWeight: 600,
    fontSize: 13,
    color: "#4a4a4a",
    display: "flex",
    flexDirection: "column",
    gap: 6,
    border: "1.5px solid #ececec",
    boxShadow: "0 1px 4px rgba(60,60,60,0.04)",
    textAlign: "center",
    "&:hover": {
      background: "#e3f2fd",
      color: "#4a4a4a",
      borderColor: "#b6c6e3",
    },
    "&.Mui-selected": {
      background: "#e6eaf3",
      color: "#2d6cdf",
      fontWeight: 700,
      borderColor: "#2d6cdf",
      boxShadow: "0 2px 8px rgba(45,108,223,0.08)",
      "& + .MuiTabs-indicator": {
        backgroundColor: "#2d6cdf",
      },
    },
    [theme.breakpoints.down("sm")]: {
      minHeight: 60,
      width: 60,
      height: 60,
      padding: "4px 4px",
      fontSize: 11,
    },
  },
  wrapper: {
    display: "flex",
    alignItems: "center",
    gap: 10,
  },
  divider: {
    width: "100%",
    height: 0.5,
    backgroundColor: "#e0e0e0", // Màu xám nhẹ giống hình ảnh
    margin: "8px 0", // Khoảng cách trên và dưới
  },
  lichchieuTitle: {
    fontWeight: 700,
    fontSize: 36,
    marginBottom: 18,
    color: "#111",
    letterSpacing: 0.5,
    fontFamily: "Montserrat, sans-serif",
    textAlign: "left",
    lineHeight: 1.2,
  },
  sidebarTitle: {
    fontWeight: 700,
    fontSize: 28,
    marginBottom: 18,
    color: "#111",
    fontFamily: "Montserrat, sans-serif",
    textAlign: "left",
    lineHeight: 1.2,
  },
  chonLichChieuWrapper: {
    background: "#fff",
    borderRadius: 18,
    border: "1.5px solid #e0e0e0",
    boxShadow: "0 2px 16px 0 rgba(45,108,223,0.06)",
    padding: "24px 24px",
    margin: "0 auto",
    maxWidth: 1200,
    display: "flex",
    flexDirection: "column",
    alignItems: "stretch",
  },
  dividerVertical: {
    width: 1.5,
    minWidth: 1.5,
    height: 40,
    background: "#e0e0e0",
    margin: "0 18px",
    alignSelf: "center",
  },
}));

export default useStyles;