import { makeStyles } from "@material-ui/core";

const useStyles = makeStyles((theme) => ({
  flexCumRap: {
    display: "flex",
    flexDirection: "row",
    gap: 20,
    width: "100%",
    maxWidth: "1400px",
    margin: "0 auto",
    padding: "20px 40px",
    background: "#fff",
    border: "1px solid #ececec",
    borderRadius: 8,
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.1)",
    [theme.breakpoints.down("sm")]: {
      flexDirection: "column",
      gap: 10,
      padding: "10px 20px",
    },
  },
  lstCumRapContainer: {
    flex: 1,
    minWidth: 300,
    maxWidth: 350,
    background: "#f7f7fa",
    border: "1px solid #ececec",
    borderRadius: 8,
    [theme.breakpoints.down("sm")]: {
      minWidth: "100%",
      maxWidth: "100%",
    },
  },
  searchContainer: {
    padding: "10px 16px",
  },
  searchInput: {
    width: "100%",
    padding: "8px 12px",
    border: "1px solid #ececec",
    borderRadius: 8,
    fontSize: 14,
    outline: "none",
    "&:focus": {
      borderColor: "#2d6cdf",
      boxShadow: "0 0 5px rgba(45, 108, 223, 0.3)",
    },
  },
  lstCumRap: {
    display: "flex",
    flexDirection: "column",
    gap: 15,
    overflowY: "auto",
    maxHeight: 500,
    padding: "16px 0",
    ...theme.customScrollbar,
    [theme.breakpoints.down("sm")]: {
      maxHeight: 300,
      padding: "8px 0",
    },
  },
  cumRap: {
    display: "flex",
    alignItems: "flex-start",
    gap: 12,
    padding: "12px 18px",
    borderBottom: "1.5px solid #ececec",
    cursor: "pointer",
    borderRadius: 10,
    background: "#fff",
    border: "1.5px solid #ececec",
    transition: "background 0.2s, box-shadow 0.2s, border-color 0.2s, opacity 0.2s",
    boxShadow: "0 1px 4px rgba(60,60,60,0.04)",
    opacity: 1,
    "&:hover": {
      background: "#e6eaf3",
      boxShadow: "0 4px 12px rgba(45,108,223,0.15)",
      borderColor: "#2d6cdf",
      opacity: 1,
    },
    [theme.breakpoints.down("sm")]: {
      flexDirection: "column",
      alignItems: "center",
      minWidth: 180,
      borderBottom: "none",
      margin: "0 8px",
    },
  },
  cumRap__img: {
    width: 48,
    height: 48,
    borderRadius: 8,
    objectFit: "cover",
    boxShadow: "0 2px 8px 0 rgba(60,60,60,0.08)",
    background: "#f7f7fa",
    [theme.breakpoints.down("sm")]: {
      width: 40,
      height: 40,
    },
  },
  cumRap__info: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    [theme.breakpoints.down("sm")]: {
      alignItems: "center",
      textAlign: "center",
    },
  },
  cumRap__address: {
    fontSize: 13,
    color: "#2d6cdf",
    marginTop: 2,
    fontStyle: "italic",
    [theme.breakpoints.down("sm")]: {
      fontSize: 12,
    },
  },
  cumRapActive: {
    background: "#e6eaf3",
    boxShadow: "0 2px 12px 0 rgba(45,108,223,0.12)",
    borderColor: "#2d6cdf",
    opacity: 1,
    transition: "background 0.2s, box-shadow 0.2s, border-color 0.2s",
  },
  rightSection: {
    flex: 3,
    background: "#fff",
    border: "1px solid #ececec",
    borderRadius: 8,
    [theme.breakpoints.down("sm")]: {
      flex: "none",
    },
  },
  theaterInfo: {
    padding: "10px 16px",
    borderBottom: "1px solid #ececec",
    marginBottom: "10px",
    fontSize: 16,
    color: "#333",
  },

  dateSelector: {
    display: "flex",
    gap: 12,
    padding: "12px 0",
    marginBottom: 16,
    flexWrap: "wrap",
  },
  dateItem: {
    padding: "10px 16px",
    minWidth: 56,
    borderRadius: 8,
    background: "#f5f5f5",
    border: "1px solid #ddd",
    cursor: "pointer",
    fontWeight: 600,
    fontSize: 14,
    color: "#333",
    textAlign: "center",
    '&:hover': {
      background: "#e0e7ff",
      borderColor: "#3f51b5",
      color: "#3f51b5",
    },
  },
  dateItemActive: {
    background: "#3f51b5",
    color: "#fff",
    borderColor: "#3f51b5",
  },
  lstPhim: {
    display: "flex",
    flexDirection: "column",
    gap: 15,
    overflowY: "auto",
    maxHeight: "calc(100vh - 300px)",
    padding: "16px 0",
    background: "#f7f7fa",
    ...theme.customScrollbar,
    [theme.breakpoints.down("sm")]: {
      maxHeight: "calc(100vh - 250px)",
      padding: "8px 0",
    },
  },
  "&:focus": {
    borderColor: "#2d6cdf",
    boxShadow: "0 0 5px rgba(45, 108, 223, 0.25)",
  },
}));

export default useStyles;